spring:
    datasource:
        url: jdbc:mysql://${app.database.port}/${app.database.name}?${app.database.options}
        username: ${app.database.username}
        password: ${app.database.password}
app:
    database:
        port: localhost:3306
        name: mybatis_flex
        username: root
        password: 12345678
        options: useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
mybatis-flex:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    type-aliases-package: usts.pycro.mybatisflex.entity